apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 네임스페이스 설정
namespace: dev-template
namePrefix: dev-
resources:
- ../../base
- namespace.yaml
labels:
patches:
- target:
    kind: Deployment
    name: fe-deployment
  path: env.json
- target:
    kind: Deployment
    name: be-deployment
  path: env.json
- target:
    kind: Ingress
    name: fe-ingress
  path: domain.json
- target:
    kind: Ingress
    name: be-ingress
  path: domain.json
images:
- name: registry.scg.skku.ac.kr/cs-grad-thesis-fe
  newTag: dev1
- name: registry.scg.skku.ac.kr/cs-grad-thesis-be
  newTag: dev0
