apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/fe-name: fe
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/fe-name: fe
    spec:
      containers:
        # 컨테이너 이미지 설정
        - image: registry.scg.skku.ac.kr/cs-grad-thesis-fe
          imagePullPolicy: Always
          name: fe
          ports:
            # 컨테이너 포트 설정
            - containerPort: 3000
          envFrom:
           - configMapRef:
               name: configmap
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  ports:
    - port: 80
      # 컨테이너 포트 설정
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/fe-name: fe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fe-ingress
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-clusterissuer'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        # 도메인 설정
        - blabla.scg.skku.ac.kr
      secretName: gitops-tls
  rules:
    # 도메인 설정
    - host: blabla.scg.skku.ac.kr
      http:
        paths:
          - backend:
              service:
                name: fe-service
                port:
                  number: 80
            path: /
            pathType: Prefix
